### ISSUE TITLE
ETQ utilisateur je peux m'authentifier

### ISSUE THREAD

**Issue by mancelin** [etalab/catalogage-donnees#12]
Maquette : https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE

## User Story

En tant qu'utilisateur,
Je souhaite m'authentifier,
Afin d'avoir accès à l'outil de façon sécurisée

## Parcours

* J'accède à l'outil
* Je me connecte avec mon compte utilisateur
* Une fois connecté j'ai accès à l'ensemble de l'outil

## Design

Maquette accueil non connecté : https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE
Maquette oubli de mot de passe : https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=1013%3A29110
Maquette confirmation d'envoi : https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=1013%3A31693
## Critères d'acceptation

- [x] Must have (MVP) : 
  - Une personne qui n'est pas connectée n'a accès à aucune fonctionnalité (au sens [features MVP](https://github.com/etalab/catalogage-donnees/milestone/1)). Seule la page "login" est accessible. Toute autre URL redirige vers la page login.
  - Une personne peut se connecter à un compte unique créé par les développeurs (avec un identifiant et un mot de passe "demo")
- [ ] Must have (post-MVP) :
  - Une personne peut créer un compte avec son adresse email
  - Une personne est rattachée à une organisation (un catalogue) lorsqu'elle crée son compte
  - ...
- [ ] Should have :
  - Certaines fonctionnalités accessibles sans authentification (lesquelles ? par exemple parcourir le contenu des catalogues en open data ?)
 - Un responsable peut inviter des personnes à créer un compte
 - Une personne peut récupérer son mot de passe avec son adresse email
  - ...
 
## Implem technique

- [x] Auth basique par email #13 
- [ ] Permissions user/admin #20 
- [x] #106
- [x] #107

**Comment by florimondmanca** [comment]
@johanricher Hello, j'ai mis à jour cette issue au format "User story" utilisé sur les autres epics. J'ai rempli ce qui me semblait pertinent. Qu'envisagerais-tu comme critères d'acceptation ?

**Comment by florimondmanca** [comment]
@johanricher Je serais tenté de rajouter quelque chose dans le "MVP" : qu'on ne puisse accéder au reste du site que si l'on est connecté.

(Concrètement, si on n'est pas connecté et qu'on accède à une URL quelconque, on doit être redirigé sur la page de login.)

**Comment by johanricher** [comment]
Oui effectivement c'est bien le comportement attendu. :+1:

**Comment by johanricher** [comment]
Ce parcours utilisateur "MVP" est complet, il sera complété notamment avec le chantier #122, #124, etc.
