### ISSUE TITLE
Gestion multi-catalogue

### ISSUE THREAD

**Issue by johanricher** [etalab/catalogage-donnees#122]
Dépend de :
* #124
* #334
* #284

## Critères d'acceptation

(Sur l'instance de prod)

On peut considérer que, du point de vue utilisateur, la "gestion multi-catalogue" est implémentée si :

* [x] au moins deux organisations existent avec chacune leur catalogue
* [x] un utilisateur peut se connecter et consulter les catalogues d'au moins une autre organisation autre que la sienne
* [x] un utilisateur connecté peut contribuer au catalogue de son organisation

## Implémentation

* [x] #388
* [x] #389

**Comment by DaFrenchFrog** [comment]
@johanricher Etant donné son nom j'ajoute mes propositions dans ce ticket je te laisse voir comment "jardiner" ça. Voici une option qui me semble répondre à plusieurs problématiques.

**Un catalogue contient des jeux de données :**
Lors de la création d'un jeu de données, on décide du catalogue dans lequel ce jeu de données est ajouté.

**Le schéma d'un catalogue est standardisé, mais peut être complété par des champs supplémentaires :**
Cela permet de répondre à un besoin de identifié de pouvoir avoir d'autres champs que ceux définis dans le schéma standard pour répondre à des besoins métiers spécifiques. Cette proposition vient remplacer la proposition #44 qui serait du coup moins pertinente. 
Conséquence : ETQ réutilisateur quand je fais une recherche dans un catalogue je peux utiliser les champs complémentaires comme critère de recherche.

**Les catalogues sont indépendants des organisations :**
Une organisation peut avoir plusieurs catalogues, et un catalogue peut être administré par plusieurs organisations. Cela permet une meilleure coopération entre les organisations qui partagent des données identiques, et permet une meilleure granularité au sein des différents services.

**Chaque utilisateur peut créer son propre catalogue :**
Il en devient administrateur de fait. Cela permet plus d'ouverture et donne la possibilité à chacun de produire ses données. 

**Tous les catalogues sont publics :** 
Les catalogues ne contiennent pas en soi d'informations sensibles et n'ont donc pas de raisons de ne pas être accessibles aux autres organisations.

**Comment by johanricher** [comment]
En effet cet "epic" constitue un chantier particulièrement vaste car en lien avec beaucoup d'aspects fonctionnels différents. Il faudra donc détailler ça en différents tickets. Il s'agit d'explorer justement les conséquences de rendre l'outil multi-tenant (ce qu'il n'est pas à l'heure actuelle), d'identifier les angles morts, de déterminer par quel bout il convient de démarrer le chantier, etc.

> Une organisation peut avoir plusieurs catalogues
> Chaque utilisateur peut créer son propre catalogue

Quel problème cela résout du point de vue utilisateur ? comparé à la complexité d'implémentation et de design, est-ce que c'est un calcul gagnant ? A explorer mais cela me paraît bien trop tôt pour envisager ça.

> un catalogue peut être administré par plusieurs organisations.

Cela aurait pour conséquence directe que n'importe qui peut contribuer à tous les catalogues de toutes les organisations. Je ne pense pas que les organisations seront d'accord avec ce fonctionnement, par conqéquent elles demanderont une instrumentation complexe de cette gouvernance (attribuer des droits sur leur catalogue à certaines personnes, certains services, certains ministères pour faire certaines choses, etc.). 

Un membre d'une organisation a une légitimité, de fait, à pouvoir contribuer au catalogue de son organisation. Ce principe de base, simple et logique, ne nécessite aucune instrumentation supplémentaire et me paraît un point de départ assez solide. Il s'agira de voir si des problèmes se présentent remettant en question ce fonctionnement et justifient qu'on complexifie le système.

**Comment by DaFrenchFrog** [comment]
> Quel problème cela résout du point de vue utilisateur ? comparé à la complexité d'implémentation et de design, est-ce que c'est un calcul gagnant ? A explorer mais cela me paraît bien trop tôt pour envisager ça.

Selon moi (et c'est donc à valider avec les pilotes) le fait d'avoir plusieurs catalogues pour une même organisation permet pour les grands ministères de diviser les catalogues en plusieurs parties. Est-ce que la DRAC Bretagne ne souhaitera pas à moment gérer son propre catalogue pour ses propres données ? Est-ce que l'Ecolab du MTE ne souhaiterait pas gérer son propre catalogue ? A vérifier...

Pour le reste c'est un point qui avait été remonté mais il est probablement mineur et on peut effectivement encore attendre.

**Comment by johanricher** [comment]
> Est-ce que la DRAC Bretagne ne souhaitera pas à un moment gérer son propre catalogue pour ses propres données

**Comment by florimondmanca** [comment]
@johanricher Je réponds ici à ta question sur Mattermost à propos du modèle de multi-tenant qu'on utiliserait.

> On est en train de construire une application multi-tenant c'est à dire qu'on a un seul service utilisés par plusieurs organisations (avec chacune leurs utilisateurs et catalogues isolés). Est-ce que ça veut dire en pratique qu'on a une seule table pour tous les utilisateurs de l'application ou est-ce qu'on a plusieurs tables (voire plusieurs BDD) ?

En effet le multi-tenant consiste à servir plusieurs organisations à partir d'une même instance logicielle : un même serveur web, un même serveur DB. La subtilité est qu'un serveur de DB peut avoir plusieurs DB en son sein. Par ex notre serveur PostgreSQL chez Scaleway a actuellement 3 DB : staging, demo, sandbox.

Ça peut se faire par plusieurs niveaux d'isolation "physique"...

Niveau 1 : une DB par tenant (au sein du même serveur de DB). Ça me semble adapté dans le cas d'une forte séparation des données, par ex un SaaS où chaque organisation n'a absolument rien à voir l'une avec l'autre, voire doit être le plus séparée possible (ex : données sensibles). Il me semble que ce n'est pas notre cas, car il faut pouvoir partager les catalogues inter/publics entre ministères.

Niveau 2 : 1 seule DB, mais plusieurs "[schémas](https://www.postgresql.org/docs/current/ddl-schemas.html)" (notion PostgreSQL). Chaque tenant a sa 'version' de chaque table, et il est possible de faire des liens entre les schémas et donc de partager des données. Mais de ce que je lis, le coût opérationnel est grand car il faut gérer les migrations dans chaque schéma indépendamment. Niveau perf ça ne semble pas optimal non plus si on doit très souvent accéder à des donneés partagées entre les schémas (je ne sais pas ce que ça donnera avec 10 ou + ministères).

Niveau 3 _(option actuelle ?)_ : utiliser les mêmes tables dans la même DB, mais avoir une colonne d'identification du tenant. Ici ce serait le rôle de `organization_id`. Le principal défi est alors de l'ordre de l'implémentation : bien filtrer avec du `WHERE organization_id = ...` partout où c'est nécessaire. Le partage de données efficace est facilité car on peut faciliter réaliser des jointures avec des indexes partagés.

Niveau 4 : appliquer une "[row-level policy](https://www.postgresql.org/docs/14/ddl-rowsecurity.html)", un mécanisme PostgreSQL qui permet de définir selon quelle condition un utilisateur PostgreSQL peut effectuer telle opération (select, insert, update, delete) sur telle table. Ça me semble plus approprié pour les usages type data mining avec accès partagé à une BDD où il y a en effet plusieurs utilisateurs PostgreSQL assignés à différents rôles. Dans notre cas, et pour un SaaS assez généralement, il n'y a qu'un seul utilisateur DB (le serveur web), donc ce niveau n'est pas applicable.

**Comment by johanricher** [comment]
C'est validé :tada:
