### ISSUE TITLE
Implémenter le schéma du catalogue

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#125]
## Contexte

Dans le cadre du [jalon du 5 mai](https://github.com/etalab/catalogage-donnees/milestone/2), nous déployons une instance de l'outil de catalogage qui contiendra un seul catalogue : celui du ministère de la Culture (MC).

Le schéma du catalogue est ce qui définit la liste des champs permettant de décrire un jeu de données présent dans un catalogue : titre, description, formats...

Il faut compléter avec les champs prévus de façon solides mais manquants aujourd'hui (_même si la fiche ne sera jamais vraiment "complète"_)

Il y a à la fois du travail back (BDD, API, modèles de données) et front (affichage)

* Un [schéma de catalogage des données](https://github.com/etalab/schema-catalogue-donnees) a été créé en 2021 avec certaines parties prenantes.
* Ce schéma est théorique pour l'instant, personne ne l'utilise, par conséquent si on se rend compte qu'il n'est pas adapté, il est préférable de faire d'abord évoluer notre implémentation (move fast, break things) et on répercutera les changements à faire dans le schéma par la suite.
* Le cas d'usage du MC détermine les critères d'acceptation de ce ticket.
* Les champs optionnels peuvent ne pas être remplis par l'utilisateur
* Certains champs pourraient être remplis automatiquement par l'outil. Par exemple le champ `siret_orga` (numéro SIRET du producteur du jeu de données) est le même pour tous les jeux de données de l'organisation il ne devrait donc être saisi qu'une fois (par un administrateur dans les paramètres du catalogue par exemple).

## Tableau récapitulatif

Source de vérité pour l'implémentation : https://lite.framacalc.org/0c5a3v0z3t-9th0

## Design

Maquette contribution : https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=843%3A22535
Maquette visualisation : https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=843%3A22296

## Critères d'acceptation

Le schéma correspond aux besoins du MC.

## Tâches

- [x] Champ "Adresse mail fonctionnelle" #150
- [x] Champ "Adresses mail contact" #152
- [x] Mots clés #160 
  - [x] API #180 
  - [x] Front
- [x] last_updated_at, update_frequency, service
  - [x] API #157 
  - [x] Front #162 
- [x] geographical_coverage, technical_source
  - [x] API #178 
  - [x] Front #177 
- [x] url #191
- [x] #179

**Comment by florimondmanca** [comment]
Hello,

Pour info je priorise comme ça : je vais d'abord ajouter les champs dans un seul formulaire "colonne", puis on pourra voir ensuite pour la mise en page "wizard". (Quand Bertrand sera là on pourra paralléliser.)

@DaFrenchFrog J'avais 1 question sur l'interactivité de la partie "Contact" (onglet "Gouvernance") à laquelle je m'attaque.

Il y a des boutons "Edit" (icône :pencil2:) sur le "Service producteur" et les "Emails de contact" : qu'est-ce qui est sensé se passer quand on clique dessus ? Apparition d'un champ texte classique et disparition du bouton ? Apparition également d'un bouton "enregistrer", ou plutôt un comportement du type "enregistrer quand on quitte le champ" (save on blur) ? Utiliser tout le long un simple champ texte (sans bouton "edit" et allure "lecture seule" donc) ne serait-il pas au final plus simple ?

**Comment by DaFrenchFrog** [comment]
Il y a des déclinaisons dans certains composant que j'ai fait et que tu peux retrouver dans la page librairie (il y a un bouton d'accès direct depuis l'instance mais on pourra peut-être regarder ça demain matin si tu veux car on ne voit pas les mêmes choses sur Figma (editor/viewer).

J'ai tout de même mis à jour en fonction de tes retours pour faire quelque chose de plus simple à priori. La condition est de supprimer le champ descriptif du composant pour n'avoir que la zone de saisie, La description étant faite pour l'ensemble des champs.
Je te met le lien vers le composant source et ses déclinaison dis-moi ce que tu en penses : https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=763%3A25738

Il est à noter que je prévois (et ce sera interrogé par les tests utilisateurs mais c'est le modèle qu'utilise le ministère de la culture en tout cas) la saisie systématique d'une boite fonctionnelle (ce qui permet de pousser un peu plus sa mise en place) ainsi que des adresses de contacts personnelles en option. Je me dis qu'on pourrait par défaut mettre l'email du contributeur plutôt que le switch car plus direct, plus simple et plus visible. Mais pour l'instant je laisse comme ça en vue du test.

**Comment by florimondmanca** [comment]
OK pour les emails de contact. :) Que donne alors le bouton "Edit" du champ "Service producteur" ? Dans un premier temps comme on n'a pas d'organisations j'envisageais un champ texte simple aussi...

**Comment by DaFrenchFrog** [comment]
> Que donne alors le bouton "Edit" du champ "Service producteur" ? Dans un premier temps comme on n'a pas d'organisations j'envisageais un champ texte simple aussi...

Oui on peut faire comme ça pour commencer et on verra si on fait évoluer ensuite

**Comment by DaFrenchFrog** [comment]
@florimondmanca @Volubyl est-ce qu'on détaille les specifications détaillées dans le tableau ? Je rajoute une colonne ? Vous préférez quoi ?

**Comment by Volubyl** [comment]
Je suis assez preneur si tu as des infos concernant un fonctionement particulier pour un champs (auto-complétion, ...)

**Comment by Volubyl** [comment]
@DaFrenchFrog  petites question niveau maquette :

1.  si je regarde ceci : https://www.figma.com/proto/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=843%3A22535&scaling=min-zoom&page-id=431%3A11368&starting-point-node-id=690%3A22060&show-proto-sidebar=1 je vois que cette page n'a pas de header avec le logo "cataloguage de donnée".

Est-ce que c'est uniquement un type de page particulier (genre la landing page) qui aura cet en-tête ? Dans quels cas il faudra avoir cet en-tête ?

2.  j'ai un doute concernant le champs "Date de la dernière mise à jour"

Dans le tableau que Florimond à fait j'imagine que ce champs correspond à `last_updated_at`

Vu la nomenclature du truc, je me dis que ça correspond à la date à laquelle le jeu de donnée à été mis à jour. Si c'est ça on pourrait imaginer que cette date soit mise à jour automatiquement dès qu'il y a une modification concernant le jeu de donnée.

Par contre en voyant la maquette, j'ai un doute ... 

Pour toi quel serait l'usage du champs  "Date de la dernière mise à jour" ?

**Comment by DaFrenchFrog** [comment]
1) Je propose de ne pas mettre de header lorsque l'on commence la contribution et de le remplacer par un simple titre et un bouton fermer (en position fixed). Je comprends que cela puisse paraitre un peu bizarre au premier abord mais voici les raisons qui m'ont poussé à faire ce choix :
- Il est de notoriété publique que le header du DSFR est très haut et prend bcp de place à l'écran. C'est très dommageable pour les petits écrans et pénalise la lisibilité et la lecture d'une page pour un contenu qui n'est que ponctuellement utile (sans avoir de chiffres pour étayer je constate par ailleurs qu'il y a bien plus de petits écrans depuis la mise en télétravail des agents de l'État et l'octroi de portables qui vont avec, portables qui souvent ont de petites résolutions). 
- Le formulaire est maintenant assez long, et dans cette partie du parcours utilisateur on ne navigue plus. On a un objectif c'est de contribuer son jeu de donnée. On rentre donc en vase clos et il me semble pertinent de faire toute la place pour ce parcours. A travers cela on renforce en quelque sorte la capacité de concentration de l'utilisateur pour terminer son formulaire. Si toutefois on veut en sortir il reste très simple et évident de cliquer sur la croix en haut à droite (qui proposera de sauvegarder la saisie (très très important) mais ça c'est pour plus tard ;) )
- Enfin, parmi les trois personnes qui ont testé le prototype il n'y a pas eu de remarques sur ce fait, ce qui même s'il nous faudra encore d'autres témoignages laisse penser que ce n'est pas forcément gênant.

Voilà dites-moi ce que vous en pensez.

2) @florimondmanca a raison. J'ai changé le wording pour mettre "Date de la dernière mise à jour des données (JJ/MM/AAAA)". Dans l'intitulé on ne parle ni de "fiche" ni de "jeu" mais on comprend qu'il s'agit des données en elle-même à priori. Cela me semble plus accessible aux béotiens que nous sommes... :)

**Comment by Volubyl** [comment]
> Je propose de ne pas mettre de header lorsque l'on commence la contribution et de le remplacer par un simple titre et un bouton fermer (en position fixed). Je comprends que cela puisse paraitre un peu bizarre au premier abord mais voici les raisons qui m'ont poussé à faire ce choix 

Merci pour les explications ! Pour moi c'est implémentable pour mai. Je me prépare une issue dédiée

**Comment by Volubyl** [comment]
>. J'ai changé le wording pour mettre "Date de la dernière mise à jour des données (JJ/MM/AAAA)". Dans l'intitulé on ne parle ni de "fiche" ni de "jeu" mais on comprend qu'il s'agit des données en elle-même à priori. Cela me semble plus accessible aux béotiens que nous sommes... :)

Je pense que j'aurai besoin d'éclaircicement à l'oral :sweat_smile:. Ca sera plus simple pour moi d'assimiler ce vocabulaire métier !

**Comment by johanricher** [comment]
J'ai mis à jour la description de ce ticket et créé #166 afin de bien distinguer les 2 sujets.

**Comment by Volubyl** [comment]
@DaFrenchFrog j'ai un questionnement par rapport à ce champ
![si](https://user-images.githubusercontent.com/15958334/163385598-d9728617-5251-4311-a76b-1e9d3c918812.png)
s

Pourrait tu me décrire le comportement attendu par rapport à ce champ ?

C'est la partie "[..] Séparez leur nom par des “/” lorsqu’il y en a plusieurs." qui me laisse perplexe.

Est-ce que l'on s'attend à avoir une chaine de caractère avec des "/" dedans ou faut il considéré chaque élément séparé par ces "/" comme des éléments individuels ?

Exemple : "foo/bar" sera  enregistré "foo"  et  "bar ou ""foo/bar"  sera enregistré comme "foo/bar"

**Comment by DaFrenchFrog** [comment]
Je ne sais pas encore à quel point ce sera pertinent de pouvoir saisir plusieurs SI sources. Si ce n'est pas trop gênant de passer plus tard sur "foo" et "bar" je pense que dans un premier temps il faut mieux enregistrer avec "foo/bar" pour rester simple. Si on voit que c'est utilisé je prévois de pouvoir ajouter des champs individuels pour chaque SI source.
