### ISSUE TITLE
Améliorations mineures

### ISSUE THREAD

**Issue by DaFrenchFrog** [etalab/catalogage-donnees#209]
Cette liste est non exhaustive. Je me dis que je pourrai la mettre à jour au fur et à mesure car je sais qu'il y a des éléments qui n'ont pas encore été implémentés, ou des retours qui sont en priorité (très) basse... :)

### Header

- [x]  Remplacer le texte "Catalogage des données" par "Catalogue Interministériel des Données" (le C.I.D. ???)
- [x] Supprimer le texte "Un outil pour cataloguer les jeux de données des différents ministères"

### Page d'accueil 
- [x] A la place du titre "Dernières contributions" mettre "XXX jeux de donnnées contribués" 
- [x] Ticket #206
- [x] Ajouter le statut open data sur la carte #222

### Page Rechercher
- [x] Mettre le même bloc que sur la page d'accueil #223 
- [x] Lorsqu'il n'y a pas de recherche lancée supprimer "0 résultats" #223 
- [x] Dans les résultats de recherche, si le terme recherché n'est pas présent dans le descriptif, ne pas l'afficher #255

### Page Contribuer
- [x] ~Mettre le header (titre + bouton fermer) en position:fixed pour pouvoir fermer à tout moment la fenêtre~ Déplacé vers #221
- [x] Mettre la rubrique du menu en highlight selon la position du scroll dans la page. Et si le menu de gauche ne peut pas "suivre" le scroll en terme d'activation du menu je pense qu'il vaut mieux n'avoir aucun item actif https://github.com/etalab/catalogage-donnees/issues/217
- [x] Ajouter une marge sur les champs de formulaire comme sur [la maquette](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=1482%3A46062)
- [ ] Remplacer "Publier ce jeu de données" par "Publier la fiche de données". A mon sens on ne publie pas un jeu de données mais une fiche qui décrit un jeu de données #264
-  [x] Ajouter une marge sous le bouton "Publier" 

### Fiche de données
- [x] Ajouter les tags sous le titre (ils n'étaient pas dans les maquettes) #219 
- [x] Ajouter le statut d'ouverture de la fiche : open data+lien ou restreint #222 
- [x] Il y a une différence de couleur du texte entre la maquette et le site (manque de contraste) #258
Sur le site : 
<img width="219" alt="image" src="https://user-images.githubusercontent.com/25462034/165791262-0d02d000-9420-43cd-9283-4b3c5386054c.png">
Sur la maquette :
<img width="223" alt="image" src="https://user-images.githubusercontent.com/25462034/165791370-4b76da8c-8ab7-4f04-8b44-07eb3eb277d3.png">

**Comment by Volubyl** [comment]
@DaFrenchFrog plusieures questions. 

## Page Rechercher
> Mettre le même bloc que sur la page d'accueil

Tu parles de quel bloc ? Celu-ci 
![searcn](https://user-images.githubusercontent.com/15958334/166687084-08e36f9b-d751-4bcc-b801-26ab313f4da8.png)

## Page contribuer

Question générale : est-ce que tes remarques prenaient déja en compte la "refonte" de la page contribuer (cfr la version sur staging) ?

**Comment by Volubyl** [comment]
Aussi j'ai créer une issue spécifique pour "Mettre la rubrique du menu en highlight selon la position du scroll dans la page"

Voir #217

**Comment by DaFrenchFrog** [comment]
Merci !

**Page recherche :** Oui c'est ce bloc là mais à noter que cette demande peut entrer en contradiction avec le sujet #212 en discussion.

**Page contribuer :** Oui il s'agit de ce bloc, et pour la page contribuer, après relecture et revisite de staging j'ai modifié le ticket...

**Comment by florimondmanca** [comment]
> Les tags pourraient renvoyer sur les résultats de recherche filtrée par ce dernier ?

À terme pourquoi pas, par contre ce ne serait pas juste mineur comme changement, car une telle recherche par tag n'est pas encore implémentée. Par conséquent si j'ai bien compris les tags seraient gris pour l'instant dans la page d'une fiche de données, si on reste cohérents avec le DSFR.

**Comment by DaFrenchFrog** [comment]
Le gris ne va pas convenir c'est trop "désactivé".

Mettons des badges en attendant et on les remplacera par des tags lorsque l'on implémentera les filtres avancés.

**Comment by florimondmanca** [comment]
@DaFrenchFrog À propos de la différence de couleur de texte, pour info la maquette utilise un noir pur `#000` alors que le DSFR utilise une couleur de texte par défaut d'un noir grisé qui vaut `#3a3a3a`.

Il est techniquement possible de personnaliser cela en une autre couleur. Par exemple il y a `#161616` qui est plus sombre que le gris par défaut, et qui est déjà utilisé pour les titres (h1, h2, etc). Mais le DSFR ne le documente pas, ce n'est donc pas très pérenne.

Dans #258 j'ai passé les labels en mention-grey, ce qui devrait déjà améliorer le contraste.

Soit on décide donc de déroger au DSFR pour les textes de corps, soit on considère que #258 suffit et dans ce cas peut-être vaut-il mieux faire utiliser `#3a3a3a` à la maquette également ?

**Comment by florimondmanca** [comment]
@DaFrenchFrog Il ne reste plus que cet item:

> (À débattre) Remplacer "Publier ce jeu de données" par "Publier la fiche de données". A mon sens on ne publie pas un jeu de données mais une fiche qui décrit un jeu de données

Pour ma part ça me semble OK. On y va ?
