### ISSUE TITLE
ETQ utilisateur je peux parcourir le catalogue

### ISSUE THREAD

**Issue by johanricher** [etalab/catalogage-donnees#22]
## User Story

En tant qu'utilisateur,  
je souhaite parcourir le catalogue de mon organisation,  
afin de découvrir les jeux de données dans mon organisation.

## Parcours

* Je me connecte à l'outil avec mon compte utilisateur
* Une fois connecté j'arrive sur une page qui liste tous les jeux de données de mon organisation
* En cliquant sur le nom d'un jeu de données, je suis emméné sur une fiche qui décrit ses métadonnées

## Design

Voir [maquette page d'accueil](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE?node-id=431%3A11368)

## Critères d'acceptation

* [x] Must have (MVP) : la page d'accueil est la page qui liste tous les jeux de données de mon organisation
* [x] Must have (MVP) : La page "catalogue" est une simple liste (voir les fonctionnalités dédiées à la recherche : #66) 
* [x] Must have (MVP) : Un bouton me permet de revenir au catalogue de mon organisation depuis n'importe quelle page (par exemple la fiche d'un jeu de données)
* [ ] Should have (MVP ou après) : gestion multi-catalogue (je peux parcourir les fiches provenant des catalogues d'autres organisations si elles ont été partagées)

## Implem technique

- [x] #63
- [ ] #79
- [x] #82
- [x] #84

**Comment by johanricher** [comment]
Le parcours utilisateur "MVP" est complet, il sera amélioré notamment avec le chantier #122
