### ISSUE TITLE
Backend des filtres de recherche

### ISSUE THREAD

**Issue by florimondmanca** [etalab/catalogage-donnees#270]
Refs #126 

## Idée générale

Côté back, les filtres seront implémentés sous la forme de paramètres de requête (_query parameters_) acceptés par l'endpoint `GET /datasets/`.

La valeur d'un filtre est une liste de valeurs qui sont combinées dans une logique `OR`.

Ainsi pour une querystring de ce type :

```http
GET /datasets/?geographical_coverage=region&formats=api&formats=web
```

On obtiendra les fiches de jeu de données 1) où la couverture géo est régionale, et 2) où au moins un des formats 'api' ou 'web' est disponible.

## Liste des filtres exposés

* [x] `q`, `str`, à intégrer à la commande `GetAll` #280
* [x] #271, `List[GeographicalCoverage]`
* [ ] `service`, `List[str]` #295 
* [ ] `formats`, `List[DataFormat]` #295  
* [ ] `technical_source`, `List[str]` #295
* [x] `tags`, `List[ID]` #274 

## Endpoints

`GET /datasets/`

Existe déjà, mais il est augmenté:

* Accepte les filtres définis ci-dessus via des _query parameters_

`GET /datasets/filters/`

* Renvoie les filtres possibles selon ce format :

    ```json
    {
      "geographical_coverage": ["..."]
      "service": ["..."],
      "formats": ["..."],
      "technical_source": ["..."],
      "tags": ["..."],
    }
    ```

**Comment by florimondmanca** [comment]
@Volubyl J'ai noté ici les interfaces que l'API expose pour récupérer et envoyer les filtres côté front.

Je nous fais une pré-design review du front par écrit pour vérifier que ça suffit, si je rate des trucs dis-moi :

* Lors de l'init des filtres, on récupère les choix possibles avec un `GET /datasets/filters/`.
* On stocke l'état des filtres quelque part (un store ?).
* Quand on choisit une valeur de filtre dans son dropdown, on ajoute la valeur aux filtres.
* À mon avis, les filtres doivent être synchronisés avec l'URL. Cela permet qu'ils s'appliquent lors d'un refresh ou d'une nouvelle ouverture de page (suite au partage de l'URL avec qq'un par ex). Donc même principe que pour `?page` ou `?q` : construire la querystring à partir de l'état des filtres, et faire un `goto()` qui déclenche le `load()` qui appelle `GET /datasets/` via `getDatasets()` à partir des `searchParams` ainsi modifiés.
