### ISSUE TITLE
Améliorations mineures

### ISSUE THREAD

**Issue by DaFrenchFrog** [etalab/catalogage-donnees#372]
Je remet un ticket pour noter tous minor fix front que je vois...

### Fiche de jeu de données

Maquette [ici](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=2366%3A34655)

- [x] Remplacer le titre "catalogage des données" sous la marianne par "République Française" PR https://github.com/etalab/catalogage-donnees/pull/433
- [X] Mettre le groupe "Accès aux données" en haut de page #424
- [ ] Ajouter les autres champs commun dans la colonne de gauche #424 
- [X] Les badges mot-clés sont de taille SM (css `fr-badge--sm`) #433 
- [x] Sur ces badges il faudrait forcer le texte pour qu'il tienne sur une seule ligne, par conséquent les badges peuvent se retrouver sur plusieurs s'ils sont trop nombreux (ou trop longs). Un bon exemple d'affichage incorrect [ici](https://catalogue.multi.coop/fiches/b07760e9-c4c6-4a9d-8eb9-3ab703d8e5e5) #436 
- [ ] Le champ qui se trouve au-dessus du titre correspond en fait au champ "service" et non "nom_orga" #433
- [X] Mettre à jour le bandeau "bêta" avec la dernière version du design system [ici](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/en-tete) #433
- [x] Ajouter un sous-titre au header "Contribuer" et "Modifier" une fiche (maquette [ici](https://www.figma.com/file/42KOPuvkD1jpubEe2mMtXr/DATALOGUE-maquettes?node-id=1482%3A46062)) #426

**Comment by Volubyl** [comment]
@johanricher @DaFrenchFrog la plupart des minor fix évoqués dans cette issue ont été réalisé.

Il en reste deux qui n'ont pas été fait pcq au final ils demandent il peu plus de travail.

Pour ceux là des issues séparées ont été crées.

Je parle de #424  et de #434 

Par conséquent, est-ce que l'on pourrait fermer cette issue ?

**Comment by DaFrenchFrog** [comment]
OK pour moi.
